name: Portfolio Website

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy App
      uses: fifsky/ssh-action@master
      with:
        command: |
          git pull origin master
          cd /home/thor/apps/Portfolio-website/.github/workflows

          npm ci
          npm run build

          pm2 stop ../../ecosystem.config.js
          pm2 start ../../ecosystem.config.js

        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
