name: Portfolio Website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Source Code
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /home/thor/apps/Portfolio-website
          git pull origin master
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}

    - name: Build
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /home/thor/apps/Portfolio-website
          npm ci
          npm run build
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}

    - name: Start App
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /home/thor/apps/Portfolio-website
          pm2 stop ../../ecosystem.config.js
          pm2 start ../../ecosystem.config.js
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
